version: '3'

networks:
  laravel:

volumes:
  mysql-data:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8080:80"
    volumes: 
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: laradock
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
      